"""add_audit_log_model

Revision ID: 04713b31edad
Revises: f8993d6a844b
Create Date: 2026-01-21 18:30:23.038758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04713b31edad'
down_revision: Union[str, Sequence[str], None] = 'f8993d6a844b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target_table', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditlog_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditlog_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditlog_target_table'), ['target_table'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditlog_target_table'))
        batch_op.drop_index(batch_op.f('ix_auditlog_id'))
        batch_op.drop_index(batch_op.f('ix_auditlog_action'))

    op.drop_table('auditlog')
    # ### end Alembic commands ###
