"""add_e2ee_fields_to_message

Revision ID: 13b64001e617
Revises: 04713b31edad
Create Date: 2026-01-21 18:31:57.736755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b64001e617'
down_revision: Union[str, Sequence[str], None] = '04713b31edad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('encryption_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('encryption_hash')
        batch_op.drop_column('is_encrypted')

    # ### end Alembic commands ###
