"""add_communication_models

Revision ID: 47e5dee21cf6
Revises: 876df5e06224
Create Date: 2026-01-21 17:47:19.722875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e5dee21cf6'
down_revision: Union[str, Sequence[str], None] = '876df5e06224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forumpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forumpost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forumpost_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forumpost_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_forumpost_topic'), ['topic'], unique=False)

    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notice_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_title'), ['title'], unique=False)

    op.create_table('forumcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='fk_forumcomment_author_id'),
    sa.ForeignKeyConstraint(['post_id'], ['forumpost.id'], name='fk_forumcomment_post_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forumcomment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forumcomment_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forumcomment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forumcomment_id'))

    op.drop_table('forumcomment')
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notice_title'))
        batch_op.drop_index(batch_op.f('ix_notice_id'))

    op.drop_table('notice')
    with op.batch_alter_table('forumpost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forumpost_topic'))
        batch_op.drop_index(batch_op.f('ix_forumpost_title'))
        batch_op.drop_index(batch_op.f('ix_forumpost_id'))

    op.drop_table('forumpost')
    # ### end Alembic commands ###
