"""add_biometric_okr_maintenance_features

Revision ID: 876df5e06224
Revises: 026b03217c79
Create Date: 2026-01-21 14:40:05.194526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876df5e06224'
down_revision: Union[str, Sequence[str], None] = '026b03217c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_id'), ['id'], unique=False)

    op.create_table('okr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('key_results', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('okr', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_okr_id'), ['id'], unique=False)

    op.create_table('performancereview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('review_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_performance_employee_id'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['employee.id'], name='fk_performance_reviewer_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performancereview', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performancereview_id'), ['id'], unique=False)

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_maintenance_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('qr_code_data', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_asset_qr_code_data', ['qr_code_data'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint('uq_asset_qr_code_data', type_='unique')
        batch_op.drop_column('qr_code_data')
        batch_op.drop_column('next_maintenance_date')

    with op.batch_alter_table('performancereview', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performancereview_id'))

    op.drop_table('performancereview')
    with op.batch_alter_table('okr', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_okr_id'))

    op.drop_table('okr')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_id'))

    op.drop_table('attendance')
    # ### end Alembic commands ###
