"""add_finance_and_marketing_models

Revision ID: 95c99d732361
Revises: d606d68bae11
Create Date: 2026-01-20 16:40:53.847666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c99d732361'
down_revision: Union[str, Sequence[str], None] = 'd606d68bae11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenseapproval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenseapproval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenseapproval_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenseapproval_id'), ['id'], unique=False)

    op.create_table('marketingcampaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketingcampaign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketingcampaign_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketingcampaign_name'), ['name'], unique=False)

    op.create_table('feestructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('term', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id')
    )
    with op.batch_alter_table('feestructure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feestructure_id'), ['id'], unique=False)

    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketingcampaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_id'), ['id'], unique=False)

    op.create_table('scholarship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('scholarship_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scholarship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scholarship_id'), ['id'], unique=False)

    op.create_table('tuitioninvoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['feestructure.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tuitioninvoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tuitioninvoice_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tuitioninvoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tuitioninvoice_id'))

    op.drop_table('tuitioninvoice')
    with op.batch_alter_table('scholarship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scholarship_id'))

    op.drop_table('scholarship')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_full_name'))
        batch_op.drop_index(batch_op.f('ix_lead_email'))

    op.drop_table('lead')
    with op.batch_alter_table('feestructure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feestructure_id'))

    op.drop_table('feestructure')
    with op.batch_alter_table('marketingcampaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketingcampaign_name'))
        batch_op.drop_index(batch_op.f('ix_marketingcampaign_id'))

    op.drop_table('marketingcampaign')
    with op.batch_alter_table('expenseapproval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenseapproval_id'))
        batch_op.drop_index(batch_op.f('ix_expenseapproval_category'))

    op.drop_table('expenseapproval')
    # ### end Alembic commands ###
