"""Add program and grade models

Revision ID: d606d68bae11
Revises: 385f46a804df
Create Date: 2026-01-20 15:56:34.105585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd606d68bae11'
down_revision: Union[str, Sequence[str], None] = '385f46a804df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_code'), 'program', ['code'], unique=True)
    op.create_index(op.f('ix_program_id'), 'program', ['id'], unique=False)
    op.create_index(op.f('ix_program_name'), 'program', ['name'], unique=False)
    op.create_table('course_corequisites',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('corequisite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corequisite_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'corequisite_id')
    )
    op.create_table('course_prerequisites',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id')
    )
    op.create_table('program_course_association',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('program_id', 'course_id')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_id'), 'grade', ['id'], unique=False)
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mandatory', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hours_per_week', sa.Integer(), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_student_program', 'program', ['program_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_program', type_='foreignkey')
        batch_op.drop_column('program_id')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('hours_per_week')
        batch_op.drop_column('capacity')
        batch_op.drop_column('category')
        batch_op.drop_column('is_mandatory')
    op.drop_index(op.f('ix_grade_id'), table_name='grade')
    op.drop_table('grade')
    op.drop_table('program_course_association')
    op.drop_table('course_prerequisites')
    op.drop_table('course_corequisites')
    op.drop_index(op.f('ix_program_name'), table_name='program')
    op.drop_index(op.f('ix_program_id'), table_name='program')
    op.drop_index(op.f('ix_program_code'), table_name='program')
    op.drop_table('program')
    # ### end Alembic commands ###
