"""add_installments_and_vendors

Revision ID: ddaf292dfbf1
Revises: 95c99d732361
Create Date: 2026-01-20 17:07:37.455997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddaf292dfbf1'
down_revision: Union[str, Sequence[str], None] = '95c99d732361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_name'), ['name'], unique=False)

    op.create_table('tuitioninstallment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['tuitioninvoice.id'], name='fk_installment_invoice'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tuitioninstallment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tuitioninstallment_id'), ['id'], unique=False)

    with op.batch_alter_table('expenseapproval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_expense_vendor', 'vendor', ['vendor_id'], ['id'])

    with op.batch_alter_table('tuitioninvoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_fee_accumulated', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tuitioninvoice', schema=None) as batch_op:
        batch_op.drop_column('late_fee_accumulated')

    with op.batch_alter_table('expenseapproval', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vendor_id')

    with op.batch_alter_table('tuitioninstallment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tuitioninstallment_id'))

    op.drop_table('tuitioninstallment')
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_name'))
        batch_op.drop_index(batch_op.f('ix_vendor_id'))

    op.drop_table('vendor')
    # ### end Alembic commands ###
